
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HotelManagmentSystem.Models.DB
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_payment_type
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbl_payment_type()
    {

        this.tbl_booking = new HashSet<tbl_booking>();

        this.tbl_payment = new HashSet<tbl_payment>();

    }


    public int payment_type_id { get; set; }

    public string payment_type { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbl_booking> tbl_booking { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbl_payment> tbl_payment { get; set; }

}

}
