
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HotelManagmentSystem.Models.DB
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_payment
{

    public int payment_id { get; set; }

    public byte booking_id { get; set; }

    public int payment_type_id { get; set; }

    public decimal payment_amount { get; set; }

    public Nullable<bool> Is_Active { get; set; }



    public virtual tbl_payment_type tbl_payment_type { get; set; }

}

}
