
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace HotelManagmentSystem.Models.DB
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_room_type
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbl_room_type()
    {

        this.tbl_room = new HashSet<tbl_room>();

    }


    public int room_type_id { get; set; }

    public string room_name { get; set; }

    public string description { get; set; }

    public Nullable<decimal> room_price { get; set; }

    public byte room_capacity { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbl_room> tbl_room { get; set; }

}

}
